import = [
  "~/.config/alacritty/gruvbox.toml"
]

[window]
padding = { x = 20, y = 20 }

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.offset]
y = 2

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"
